/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ModelController.BanAnController;
import DAO.ModelDAO.BanAnDAO;
import DAO.impl.BanAnImpl;
import Model.BanAn;
import Util.UDialog;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baoha
 */
public class BanAnView extends javax.swing.JPanel implements BanAnController{
    BanAnDAO dao = new BanAnImpl();
    List<BanAn> items = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BanAnView.class.getName());

    /**
     * Creates new form BanAn
     */
    public BanAnView(boolean visible) {
        initComponents();
        filltoCombo();
        setButtonVisible(visible);
    }
    public void setButtonVisible(boolean visible) {
    jButton1.setVisible(visible);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanAn = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboMaKV = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnTiemkiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSoluongBan = new javax.swing.JTextField();
        btnvecuoi = new javax.swing.JButton();
        btntien = new javax.swing.JButton();
        btntruoc = new javax.swing.JButton();
        btnvedau = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 690));

        tblBanAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã bàn", "Số bàn", "Trạng thái", "Mã khu vực"
            }
        ));
        tblBanAn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblBanAnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblBanAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBanAn);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 172, 1920, 910));

        jPanel4.setBackground(new java.awt.Color(173, 139, 115));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản Lý Bàn Ăn");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1802, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        add(cboMaKV, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 134, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, -1, -1));
        add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 112, 258, -1));

        btnTiemkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnTiemkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiemkiemActionPerformed(evt);
            }
        });
        add(btnTiemkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 97, -1, -1));

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Số lượng bàn:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        add(txtSoluongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        btnvecuoi.setBackground(new java.awt.Color(173, 139, 115));
        btnvecuoi.setText("Về cuối");
        btnvecuoi.setMaximumSize(new java.awt.Dimension(50, 20));
        btnvecuoi.setMinimumSize(new java.awt.Dimension(50, 20));
        btnvecuoi.setPreferredSize(new java.awt.Dimension(50, 20));
        btnvecuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvecuoiActionPerformed(evt);
            }
        });
        add(btnvecuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 100, 30));

        btntien.setBackground(new java.awt.Color(173, 139, 115));
        btntien.setText("Tiến");
        btntien.setMaximumSize(new java.awt.Dimension(50, 20));
        btntien.setMinimumSize(new java.awt.Dimension(50, 20));
        btntien.setPreferredSize(new java.awt.Dimension(50, 20));
        btntien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntienActionPerformed(evt);
            }
        });
        add(btntien, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 100, 30));

        btntruoc.setBackground(new java.awt.Color(173, 139, 115));
        btntruoc.setText("Trước");
        btntruoc.setMaximumSize(new java.awt.Dimension(50, 20));
        btntruoc.setMinimumSize(new java.awt.Dimension(50, 20));
        btntruoc.setPreferredSize(new java.awt.Dimension(50, 20));
        btntruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruocActionPerformed(evt);
            }
        });
        add(btntruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 90, 30));

        btnvedau.setBackground(new java.awt.Color(173, 139, 115));
        btnvedau.setText("Về đầu");
        btnvedau.setMaximumSize(new java.awt.Dimension(50, 20));
        btnvedau.setMinimumSize(new java.awt.Dimension(50, 20));
        btnvedau.setPreferredSize(new java.awt.Dimension(50, 20));
        btnvedau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvedauActionPerformed(evt);
            }
        });
        add(btnvedau, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTiemkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiemkiemActionPerformed
        // TODO add your handling code here:
        fillToTableTheoDieuKien();
    }//GEN-LAST:event_btnTiemkiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblBanAnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblBanAnAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Mã Bàn", "Số Bàn", "Trạng Thái", "Mã Khu Vực"},
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa bất kỳ ô nào
            }
        };
        tblBanAn.setModel(model);

        fillToTable();
    }//GEN-LAST:event_tblBanAnAncestorAdded

    private void tblBanAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanAnMouseClicked
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_tblBanAnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnvecuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvecuoiActionPerformed
        // TODO add your handling code here:
        moveLast();
    }//GEN-LAST:event_btnvecuoiActionPerformed

    private void btntienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntienActionPerformed
        // TODO add your handling code here:
        moveNext();
    }//GEN-LAST:event_btntienActionPerformed

    private void btntruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruocActionPerformed
        // TODO add your handling code here:
        movePrevious();
    }//GEN-LAST:event_btntruocActionPerformed

    private void btnvedauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvedauActionPerformed
        // TODO add your handling code here:
        moveFirst();

    }//GEN-LAST:event_btnvedauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTiemkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btntien;
    private javax.swing.JButton btntruoc;
    private javax.swing.JButton btnvecuoi;
    private javax.swing.JButton btnvedau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboMaKV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBanAn;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtSoluongBan;
    // End of variables declaration//GEN-END:variables
@Override
public void setForm(BanAn entity) {
    for (int i = 0; i < cboMaKV.getItemCount(); i++) {
        String item = cboMaKV.getItemAt(i); // VD: "KV01 - Tầng 1"
        if (item.startsWith(entity.getMaKV())) {
            cboMaKV.setSelectedIndex(i);
            break;
        }
    }

    // Không cần set txtSoluongBan nếu không cập nhật số lượng nữa
}

@Override
public BanAn getForm() {
    BanAn ba = new BanAn();

    String maKVFull = cboMaKV.getSelectedItem().toString(); // VD: KV01 - Tầng 1
    String[] parts = maKVFull.split(" - ");
    String maKV = parts[0];

    ba.setMaKV(maKV);
    ba.setTrangThai("Trống");

    int soBan = Integer.parseInt(txtSoluongBan.getText());
    ba.setSoBan(soBan);

    return ba;
}


@Override
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblBanAn.getModel();
    model.setRowCount(0);
    items = dao.findAll();

    for (BanAn ba : items) {
        Object[] row = {
            ba.getMaBan(),
            ba.getSoBan(),
            ba.getTrangThai(),
            ba.getMaKV()
        };
        model.addRow(row);
    }
}

public void fillToTableTheoDieuKien() {
    try {
        BanAnImpl dao = new BanAnImpl(); 
        String keyword = txtFind.getText().trim();
        List<BanAn> list = dao.findByKeyword(keyword);

        DefaultTableModel model = (DefaultTableModel) tblBanAn.getModel();
        model.setRowCount(0);

        if (list.isEmpty()) {
            UDialog.alert("Không tìm thấy kết quả.");
            return;
        }

        for (BanAn ba : list) {
            Object[] row = {
                ba.getMaBan(),
                ba.getSoBan(),
                ba.getTrangThai(),
                ba.getMaKV()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        UDialog.alert("Lỗi khi tìm bàn ăn!");
    }
}

@Override
public void edit() {
    BanAn entity = items.get(tblBanAn.getSelectedRow());
    this.setForm(entity);
}

@Override
public void create() {
    if (!checkAll()) return;

    if (UDialog.confirm("Bạn có muốn thêm bàn ăn này?")) {
        BanAn entity = this.getForm();
        dao.create(entity);
        this.fillToTable();
        this.clear();
        UDialog.alert("Thêm bàn ăn thành công!");
    }
}

@Override
public void update() {
    if (!checkAll()) return;

    if (UDialog.confirm("Bạn có chắc chắn muốn cập nhật bàn ăn này?")) {
        BanAn ba = this.getForm();
        dao.update(ba);
        this.fillToTable();
        this.clear();
        UDialog.alert("Cập nhật thành công!");
    }
}

@Override
public void delete() {
    int row = tblBanAn.getSelectedRow();
    if (row == -1) {
        UDialog.alert("Vui lòng chọn bàn ăn cần xóa!");
        return;
    }

    String maBan = tblBanAn.getValueAt(row, 0).toString(); // cột 0 là MaBan
    if (UDialog.confirm("Bạn chắc chắn muốn xóa bàn ăn này?")) {
        dao.deleteById(maBan);
        this.fillToTable();
        this.clear();
        UDialog.alert("Xóa bàn ăn thành công!");
    }
}

@Override
public void clear() {
    this.setForm(new BanAn());
}

@Override
public void moveFirst() {
    int index = tblBanAn.getSelectedRow();
    if (index == 0) {
        UDialog.alert("Đã ở vị trí đầu tiên!");
    } else {
        moveTo(0);
    }
}

@Override
public void movePrevious() {
    this.moveTo(tblBanAn.getSelectedRow() - 1);
}

@Override
public void moveNext() {
    this.moveTo(tblBanAn.getSelectedRow() + 1);
}

@Override
public void moveLast() {
    this.moveTo(tblBanAn.getRowCount() - 1);
}

@Override
public void moveTo(int rowIndex) {
    if (rowIndex < 0) {
        this.moveLast();
    } else if (rowIndex >= tblBanAn.getRowCount()) {
        this.moveFirst();
    } else {
        tblBanAn.clearSelection();
        tblBanAn.setRowSelectionInterval(rowIndex, rowIndex);
        this.edit();
    }
}

public boolean checkAll() {
    if (txtSoluongBan.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập số lượng bàn muốn thêm!");
        txtSoluongBan.requestFocus();
        return false;
    }

    try {
        int soLuong = Integer.parseInt(txtSoluongBan.getText().trim());
        if (soLuong <= 0) {
            UDialog.alert("Số lượng bàn phải lớn hơn 0!");
            txtSoluongBan.requestFocus();
            return false;
        }
    } catch (NumberFormatException e) {
        UDialog.alert("Số lượng bàn phải là số nguyên!");
        txtSoluongBan.requestFocus();
        return false;
    }

    return true;
}

    public void filltoCombo(){
        BanAnImpl dao = new BanAnImpl();
    cboMaKV.removeAllItems();
    items = dao.findAllTang(); 
    items.forEach(item -> {
        String display = item.getMaKV()+ " - " + item.getTenKV();
        cboMaKV.addItem(display);
    });
    }
    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean Checkall() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
