/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.ModelDAO.DatBanDAO;
import DAO.impl.DatBanimpl;
import DAO.impl.OrderImpl;
import Model.BanAn;
import Model.DatBan;
import Model.DatBanINFOR;
import Model.HoaDon;
import Model.KhachHang;
import Model.MonAn;
import Util.UAuth;
import Util.UDialog;
import View.ViewDatBan.ConfirmDatBan;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;
import javax.swing.JOptionPane;
/**
 *
 * @author baoha
 */
public class carddatban extends javax.swing.JPanel {
private DatBan data;
OrderImpl daor = new OrderImpl();
private KhachHang kh;
private BanAn b = new BanAn();
private ConfirmDatBan obj;
private DatBanDAO dao = new DatBanimpl();
private DatBanimpl div = new DatBanimpl();
private DBFORM dbf;

public carddatban(BanAn b, DBFORM dbf) {
    this.b = b;
    this.dbf = dbf;  // dùng tham chiếu DBFORM có sẵn, không tạo mới
    this.kh = new KhachHang();
    this.data = new DatBan();
    initComponents();
    init(); // Truyền mã KH
    gandulieu();
    setOpaque(false);
}

public void init() {
    List<DatBan> list = dao.findAll();  // Load danh sách đặt bàn từ DAO
    obj = new ConfirmDatBan(menu.getFrames()[0], true);  // Tạo dialog xác nhận
    setPreferredSize(new Dimension(330, 434));

    lblBan.setText("Mã bàn: " + b.getMaBan());
    lblNumber.setText("Số bàn: " + b.getSoBan());
}

   
public void gandulieu() {
    btnXacNhan.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String maKH = txtMaKH.getText();
            String maBan = b.getMaBan();  // đảm bảo b != null
            Date ngayDat = txtNgayDat.getDate();
            LocalTime gioDat = tPGioDat.getTime();
            String maNV = UAuth.user.getMaNV();

            // Kiểm tra ngày đặt
            if (ngayDat == null) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày đặt bàn.");
                return;
            }

            int soNguoi = 0;
            try {
                soNguoi = Integer.parseInt(txtSonguoi.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Số người không hợp lệ.");
                return;
            }

            List<DatBanINFOR> dsInfo = dbf.XacNhan(maKH, maBan, ngayDat, gioDat, soNguoi, maNV);
            if (!dsInfo.isEmpty()) {
                obj.showConfirmDatBan(dsInfo);  // ✅ chỉ gọi 1 lần
            } else {
                JOptionPane.showMessageDialog(null, "Chưa có món ăn nào được chọn.");
            }

            txtSonguoi.setText("0");
        }
    });
}


    
@Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(getBackground());
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20,20);
        
        super.paintComponent(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBan = new javax.swing.JLabel();
        btnThem = new View.themvagiam();
        jLabel1 = new javax.swing.JLabel();
        btnGiam = new View.themvagiam();
        txtSonguoi = new View.MyTextField();
        btnXacNhan = new View.themDATBAN();
        lblNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tPGioDat = new com.github.lgooddatepicker.components.TimePicker();
        txtNgayDat = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBan.setText("title");
        add(lblBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, -1));

        btnThem.setBackground(new java.awt.Color(0, 255, 0));
        btnThem.setBorder(null);
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-48.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BanDat.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 210));

        btnGiam.setBackground(new java.awt.Color(255, 0, 0));
        btnGiam.setBorder(null);
        btnGiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-minus-48.png"))); // NOI18N
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });
        add(btnGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 50, -1));

        txtSonguoi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSonguoi.setText("0");
        add(txtSonguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 40, -1));

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setBackground(new java.awt.Color(173, 139, 115));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 180, -1));

        lblNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber.setText("number");
        add(lblNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số người");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 320, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ngày đặt: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giờ đặt: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));
        add(tPGioDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, -1));
        add(txtNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));

        jLabel5.setText("Mã khách hàng:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int soluong = Integer.parseInt(txtSonguoi.getText());
        
            txtSonguoi.setText((soluong + 1)+ "");
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        // TODO add your handling code here:
        int soluong = Integer.parseInt(txtSonguoi.getText());
        if(soluong > 0 ){
            txtSonguoi.setText((soluong - 1)+ "");
        } else {
            txtSonguoi.setText("0");
        }
    }//GEN-LAST:event_btnGiamActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.themvagiam btnGiam;
    private View.themvagiam btnThem;
    private View.themDATBAN btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblNumber;
    private com.github.lgooddatepicker.components.TimePicker tPGioDat;
    private javax.swing.JTextField txtMaKH;
    private com.toedter.calendar.JDateChooser txtNgayDat;
    private View.MyTextField txtSonguoi;
    // End of variables declaration//GEN-END:variables
}
