/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ModelController.ChiTietDatBanController;
import DAO.ModelDAO.ChiTietDatBanDAO;
import DAO.impl.ChiTietDatBanImpl;
import Model.ChiTietDatBan;
import Util.UDialog;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author micro
 */
public class CTDB extends javax.swing.JPanel implements ChiTietDatBanController{
    ChiTietDatBanDAO dao = new ChiTietDatBanImpl();
    List<ChiTietDatBan> items = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChiTietDatBan.class.getName());

    /**
     * Creates new form ChiTietDatBan
     */
    public CTDB(boolean visible) {
        initComponents();
    setButtonVisible(visible);
    }
    public void setButtonVisible(boolean visible) {
    jButton1.setVisible(visible);
}    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnTiemkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietDatBan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txatGhiChu = new javax.swing.JTextArea();
        txtSoLuong = new javax.swing.JTextField();
        txtMaMon = new javax.swing.JTextField();
        txtMaDat = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 1560, 1080));

        jPanel2.setBackground(new java.awt.Color(173, 139, 115));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi Tiết Đặt Bàn");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1686, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon thêm.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 120, 110, 40));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon xóa.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 120, 110, 40));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon sửa.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 120, 110, 40));

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon làm mới.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 120, 130, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setText("Tìm kiếm:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 280, 40));

        btnTiemkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnTiemkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiemkiemActionPerformed(evt);
            }
        });
        add(btnTiemkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        tblChiTietDatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đặt", "Mã món", "Số lượng ", "Ghi chú"
            }
        ));
        tblChiTietDatBan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblChiTietDatBanAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblChiTietDatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietDatBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChiTietDatBan);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 570));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ghi chú:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 940, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Số lượng:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 880, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mã món:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 830, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã đặt:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 780, 130, -1));

        txatGhiChu.setColumns(20);
        txatGhiChu.setRows(5);
        jScrollPane2.setViewportView(txatGhiChu);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 940, 270, -1));
        add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 880, 270, 30));

        txtMaMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaMonMouseClicked(evt);
            }
        });
        txtMaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonActionPerformed(evt);
            }
        });
        add(txtMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 830, 270, 30));

        txtMaDat.setEnabled(false);
        add(txtMaDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 780, 270, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTiemkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiemkiemActionPerformed
        // TODO add your handling code here:
        fillToTableTheoDieuKien();
    }//GEN-LAST:event_btnTiemkiemActionPerformed

    private void tblChiTietDatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietDatBanMouseClicked
        edit();
    }//GEN-LAST:event_tblChiTietDatBanMouseClicked

    private void tblChiTietDatBanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblChiTietDatBanAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Mã đặt", "Mã món", "Số Lượng", "Ghi chú"},
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa bất kỳ ô nào
            }
        };
        tblChiTietDatBan.setModel(model);

        fillToTable();
    }//GEN-LAST:event_tblChiTietDatBanAncestorAdded

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed

    private void txtMaMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaMonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTiemkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblChiTietDatBan;
    private javax.swing.JTextArea txatGhiChu;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtMaDat;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
@Override
public void open() {
    throw new UnsupportedOperationException("Not supported yet.");
}

@Override
public void setForm(ChiTietDatBan entity) {
    txtMaDat.setText(entity.getMaDat());
    txtMaMon.setText(entity.getMaMon());
    txtSoLuong.setText(String.valueOf(entity.getSoLuong()));
    txatGhiChu.setText(entity.getGhiChu());
}

@Override
public ChiTietDatBan getForm() {
    ChiTietDatBan ct = new ChiTietDatBan();

    ct.setMaDat(txtMaDat.getText().trim());
    ct.setMaMon(txtMaMon.getText().trim());

    try {
        ct.setSoLuong(Integer.parseInt(txtSoLuong.getText().trim()));
    } catch (NumberFormatException e) {
        ct.setSoLuong(0); // hoặc báo lỗi
    }

    ct.setGhiChu(txatGhiChu.getText().trim());

    return ct;
}

@Override
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblChiTietDatBan.getModel();
    model.setRowCount(0);
    items = dao.findAll();

    for (ChiTietDatBan ct : items) {
        Object[] row = {
            ct.getMaDat(),
            ct.getMaMon(),
            ct.getSoLuong(),
            ct.getGhiChu()
        };
        model.addRow(row);
    }
}

@Override
public void edit() {
    ChiTietDatBan entity = items.get(tblChiTietDatBan.getSelectedRow());
    this.setForm(entity);
}

@Override
public void create() {
    if (!Checkall()) return;

    if (UDialog.confirm("Bạn thực sự muốn thêm chi tiết đặt bàn này?")) {
        ChiTietDatBan entity = this.getForm();
        dao.create(entity);
        this.fillToTable();
        this.clear();
        UDialog.alert("Đã thêm thành công");
    }
}

@Override
public void update() {
    if (!Checkall()) return;

    if (UDialog.confirm("Bạn thực sự muốn cập nhật chi tiết này?")) {
        ChiTietDatBan ct = this.getForm();
        dao.update(ct); // nếu có sp_Update thì dùng, không thì bỏ qua
        this.fillToTable();
        this.clear();
        UDialog.alert("Cập nhật thành công!");
    }
}

@Override
public void delete() {
    int row = tblChiTietDatBan.getSelectedRow();
    if (row == -1) {
        UDialog.alert("Vui lòng chọn dòng cần xóa!");
        return;
    }

    String maDat = tblChiTietDatBan.getValueAt(row, 0).toString();
    String maMon = tblChiTietDatBan.getValueAt(row, 1).toString();

    if (UDialog.confirm("Bạn chắc chắn muốn xóa chi tiết này?")) {
        dao.deleteById(maDat);
        this.fillToTable();
        this.clear();
        UDialog.alert("Xóa thành công!");
    }
}

@Override
public void clear() {
    this.setForm(new ChiTietDatBan());
}

@Override
public void moveFirst() {
    int currentIndex = tblChiTietDatBan.getSelectedRow();
    if (currentIndex == 0) {
        UDialog.alert("Đã ở vị trí đầu tiên rồi!");
    } else {
        this.moveTo(0);
    }
}

@Override
public void movePrevious() {
    this.moveTo(tblChiTietDatBan.getSelectedRow() - 1);
}

@Override
public void moveNext() {
    this.moveTo(tblChiTietDatBan.getSelectedRow() + 1);
}

@Override
public void moveLast() {
    this.moveTo(tblChiTietDatBan.getRowCount() - 1);
}

@Override
public void moveTo(int rowIndex) {
    if (rowIndex < 0) {
        this.moveLast();
    } else if (rowIndex >= tblChiTietDatBan.getRowCount()) {
        this.moveFirst();
    } else {
        tblChiTietDatBan.clearSelection();
        tblChiTietDatBan.setRowSelectionInterval(rowIndex, rowIndex);
        this.edit();
    }
}

@Override
public boolean Checkall() {
    if (txtMaDat.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập mã đặt!");
        txtMaDat.requestFocus();
        return false;
    }

    if (txtMaMon.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập mã món!");
        txtMaMon.requestFocus();
        return false;
    }

    if (txtSoLuong.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập số lượng!");
        txtSoLuong.requestFocus();
        return false;
    }

    try {
        Integer.parseInt(txtSoLuong.getText().trim());
    } catch (NumberFormatException e) {
        UDialog.alert("Số lượng phải là số!");
        txtSoLuong.requestFocus();
        return false;
    }

    return true;
}

public void fillToTableTheoDieuKien() {
    try {
        ChiTietDatBanImpl dao = new ChiTietDatBanImpl(); 
        String keyword = txtFind.getText().trim(); // tìm theo mã đặt
        List<ChiTietDatBan> list = dao.findByMaDat(keyword);

        DefaultTableModel model = (DefaultTableModel) tblChiTietDatBan.getModel();
        model.setRowCount(0);

        if (list.isEmpty()) {
            UDialog.alert("Không tìm thấy kết quả.");
            return;
        }

        for (ChiTietDatBan ct : list) {
            Object[] row = {
                ct.getMaDat(),
                ct.getMaMon(),
                ct.getSoLuong(),
                ct.getGhiChu()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        UDialog.alert("Lỗi khi tìm chi tiết đặt bàn!");
    }
}
}
