/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ModelController.ChiTietHoaDonController;
import DAO.ModelDAO.ChiTietHoaDonDAO;
import DAO.impl.ChiTietHoaDonImpl;
import Model.ChiTietHoaDon;
import Util.UDialog;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author micro
 */
public class CTHD extends javax.swing.JPanel implements ChiTietHoaDonController{
    ChiTietHoaDonDAO dao = new ChiTietHoaDonImpl();
    List<ChiTietHoaDon> items = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CTHD.class.getName());

    /**
     * Creates new form ChiTietHoaDon
     */
    public CTHD(boolean visible) {
        initComponents();
    setButtonVisible(visible);
    }
    public void setButtonVisible(boolean visible) {
    jButton1.setVisible(visible);
}/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        txtSoLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        txtMaMon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        btnDau = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();
        btnTien = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnTiemkiem = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 820));

        jPanel2.setBackground(new java.awt.Color(173, 139, 115));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi tiết hóa đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 80));

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã món", "Số lượng", "Ghi chú", "Trạng thái"
            }
        ));
        tblChiTietHoaDon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblChiTietHoaDonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChiTietHoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1410, 210));
        jPanel1.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 270, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Trạng thái:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 96, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 96, -1));
        jPanel1.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 270, -1));

        txtMaMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaMonMouseClicked(evt);
            }
        });
        txtMaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã hóa đơn:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mã món:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ghi chú:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 96, -1));

        txtMaHD.setEnabled(false);
        jPanel1.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 270, -1));
        jPanel1.add(txtTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 270, -1));

        btnDau.setBackground(new java.awt.Color(173, 139, 115));
        btnDau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDau.setText("Về đầu");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });
        jPanel1.add(btnDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 120, 50));

        btnTruoc.setBackground(new java.awt.Color(173, 139, 115));
        btnTruoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });
        jPanel1.add(btnTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 120, 50));

        btnTien.setBackground(new java.awt.Color(173, 139, 115));
        btnTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTien.setText("Tiến");
        btnTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienActionPerformed(evt);
            }
        });
        jPanel1.add(btnTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 120, 50));

        btnCuoi.setBackground(new java.awt.Color(173, 139, 115));
        btnCuoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCuoi.setText("Về cuối");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnCuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 120, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 260, -1));

        btnTiemkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnTiemkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiemkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTiemkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 30));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel1.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 80, 30));

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 80, 30));

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 80, 30));

        btnlammoi.setText("Làm mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnlammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblChiTietHoaDonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblChiTietHoaDonAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Mã Hóa Đơn", "Mã Món", "Số Lượng", "Ghi Chú", "Trạng Thái", "Mã Vận Đơn"},
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa bất kỳ ô nào
            }
        };
        tblChiTietHoaDon.setModel(model);

        fillToTable();
    }//GEN-LAST:event_tblChiTietHoaDonAncestorAdded

    private void tblChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietHoaDonMouseClicked
        edit();
    }//GEN-LAST:event_tblChiTietHoaDonMouseClicked

    private void txtMaMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaMonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonMouseClicked

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        // TODO add your handling code here:
        moveFirst();
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        movePrevious();
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienActionPerformed
        // TODO add your handling code here:
        moveNext();
    }//GEN-LAST:event_btnTienActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        // TODO add your handling code here:
        moveLast();
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void btnTiemkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiemkiemActionPerformed
        // TODO add your handling code here:
        fillToTableTheoDieuKien();
    }//GEN-LAST:event_btnTiemkiemActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        create();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnlammoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnTiemkiem;
    private javax.swing.JButton btnTien;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
@Override
public void setForm(ChiTietHoaDon entity) {
    txtMaHD.setText(entity.getMaHD());
    txtMaMon.setText(entity.getMaMon());
    txtSoLuong.setText(String.valueOf(entity.getSoLuong()));
    txtGhiChu.setText(entity.getGhiChu());
    txtTrangThai.setText(entity.getTrangThai());
    
}

@Override
public ChiTietHoaDon getForm() {
    ChiTietHoaDon ct = new ChiTietHoaDon();

    ct.setMaHD(txtMaHD.getText().trim());
    ct.setMaMon(txtMaMon.getText().trim());

    try {
        ct.setSoLuong(Integer.parseInt(txtSoLuong.getText().trim()));
    } catch (NumberFormatException e) {
        ct.setSoLuong(0);
    }

    ct.setGhiChu(txtGhiChu.getText().trim());
    ct.setTrangThai(txtTrangThai.getText().trim());
    

    return ct;
}

@Override
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
    model.setRowCount(0);
    items = dao.findAll();

    for (ChiTietHoaDon ct : items) {
        Object[] row = {
            ct.getMaHD(),
            ct.getMaMon(),
            ct.getSoLuong(),
            ct.getGhiChu(),
            ct.getTrangThai()
        };
        model.addRow(row);
    }
}

@Override
public void create() {
    if (!Checkall()) return;

    if (UDialog.confirm("Bạn muốn thêm chi tiết hóa đơn này?")) {
        ChiTietHoaDon entity = getForm();
        dao.create(entity);
        fillToTable();
        clear();
        UDialog.alert("Đã thêm thành công");
    }
}

@Override
public void update() {
    if (!Checkall()) return;

    if (UDialog.confirm("Bạn thực sự muốn cập nhật thông tin khách hàng này?")) {
        ChiTietHoaDon cthd = this.getForm();
        dao.update(cthd);
        this.fillToTable();
        this.clear();
        UDialog.alert("Cập nhật thành công!");
    }
}

@Override
public void delete() {
    int row = tblChiTietHoaDon.getSelectedRow();
    if (row == -1) {
        UDialog.alert("Vui lòng chọn dòng để xóa!");
        return;
    }

    String maHD = tblChiTietHoaDon.getValueAt(row, 0).toString();
    String maMon = tblChiTietHoaDon.getValueAt(row, 1).toString();

    if (UDialog.confirm("Bạn chắc chắn muốn xóa chi tiết này?")) {
        dao.deleteById(maHD);
        fillToTable();
        clear();
        UDialog.alert("Xóa thành công");
    }
}

@Override
public void edit() {
    ChiTietHoaDon entity = items.get(tblChiTietHoaDon.getSelectedRow());
    this.setForm(entity);
}

@Override
public void clear() {
    this.setForm(new ChiTietHoaDon());
}

@Override
public boolean Checkall() {
    if (txtMaHD.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập mã hóa đơn!");
        txtMaHD.requestFocus();
        return false;
    }

    if (txtMaMon.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập mã món!");
        txtMaMon.requestFocus();
        return false;
    }

    if (txtSoLuong.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập số lượng!");
        txtSoLuong.requestFocus();
        return false;
    }

    try {
        Integer.parseInt(txtSoLuong.getText().trim());
    } catch (NumberFormatException e) {
        UDialog.alert("Số lượng phải là số!");
        txtSoLuong.requestFocus();
        return false;
    }

    if (txtTrangThai.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập trạng thái!");
        txtTrangThai.requestFocus();
        return false;
    }


    return true;
}

@Override
public void moveFirst() {
    if (tblChiTietHoaDon.getSelectedRow() == 0) {
        UDialog.alert("Đã ở vị trí đầu tiên!");
    } else {
        moveTo(0);
    }
}

@Override
public void movePrevious() {
    moveTo(tblChiTietHoaDon.getSelectedRow() - 1);
}

@Override
public void moveNext() {
    moveTo(tblChiTietHoaDon.getSelectedRow() + 1);
}

@Override
public void moveLast() {
    moveTo(tblChiTietHoaDon.getRowCount() - 1);
}

@Override
public void moveTo(int rowIndex) {
    if (rowIndex < 0) {
        moveLast();
    } else if (rowIndex >= tblChiTietHoaDon.getRowCount()) {
        moveFirst();
    } else {
        tblChiTietHoaDon.clearSelection();
        tblChiTietHoaDon.setRowSelectionInterval(rowIndex, rowIndex);
        edit();
    }
}

public void fillToTableTheoDieuKien() {
    try {
        ChiTietHoaDonImpl dao = new ChiTietHoaDonImpl(); 
        String keyword = txtFind.getText().trim();
        List<ChiTietHoaDon> list = dao.findByKeyword(keyword);

        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setRowCount(0);

        if (list.isEmpty()) {
            UDialog.alert("Không tìm thấy kết quả.");
            return;
        }

        for (ChiTietHoaDon ct : list) {
            Object[] row = {
                ct.getMaHD(),
                ct.getMaMon(),
                ct.getSoLuong(),
                ct.getGhiChu(),
                ct.getTrangThai(),
                
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        UDialog.alert("Lỗi khi tìm kiếm!");
    }
}

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
