/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ModelController.HoaDonController;
import DAO.ModelDAO.HoaDonDAO;
import DAO.impl.HoaDonImpl;
import DAO.impl.NhanVienImpl;
import Model.HoaDon;
import Model.NhanVien;
import Util.UAuth;
import Util.UDialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class HoaDonView extends javax.swing.JPanel implements HoaDonController{
    HoaDonDAO dao = new HoaDonImpl();
    List<HoaDon> items = new ArrayList<>();
    /**
     * Creates new form HoaDon
     */
    public HoaDonView(boolean visible) {
        initComponents();
    setButtonVisible(visible);
    }
    public void setButtonVisible(boolean visible) {
    jButton1.setVisible(visible);
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();
        txtmaban = new javax.swing.JTextField();
        txtmanv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JTextField();
        cboHTTT = new javax.swing.JComboBox<>();
        dcNgayLap = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtTenKhach = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnTiemkiem = new javax.swing.JButton();
        btnvecuoi = new javax.swing.JButton();
        btntien = new javax.swing.JButton();
        btntruoc = new javax.swing.JButton();
        btnvedau = new javax.swing.JButton();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã bàn", "Mã nhân viên", "Ngày lập", "Tổng tiền", "Hình thức TT", "Tên khách hàng"
            }
        ));
        tblhoadon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblhoadonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhoadon);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 630));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mã hóa đơn:");
        jLabel2.setEnabled(false);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 860, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ngày lập:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 860, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Hình thức TT:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 940, 170, -1));

        txtmahoadon.setEnabled(false);
        add(txtmahoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 860, 270, 30));
        add(txtmaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 900, 270, 30));
        add(txtmanv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 940, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Mã bàn:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 900, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã nhân viên:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 940, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tổng tiền:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 900, 170, -1));
        add(txttongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 900, 270, 30));

        cboHTTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản" }));
        cboHTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHTTTActionPerformed(evt);
            }
        });
        add(cboHTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 940, 270, 30));
        add(dcNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 860, 270, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tên khách:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 980, 170, -1));
        add(txtTenKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 980, 270, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 1080));

        jPanel3.setBackground(new java.awt.Color(173, 139, 115));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hóa Đơn");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1686, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon thêm.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 120, 110, 40));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon xóa.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 120, 110, 40));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon sửa.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 120, 110, 40));

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon làm mới.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 120, 130, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel14.setText("Tìm kiếm:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 280, 40));

        btnTiemkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnTiemkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiemkiemActionPerformed(evt);
            }
        });
        add(btnTiemkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        btnvecuoi.setBackground(new java.awt.Color(173, 139, 115));
        btnvecuoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvecuoi.setForeground(new java.awt.Color(255, 255, 255));
        btnvecuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon về cuối.png"))); // NOI18N
        btnvecuoi.setText("Về cuối");
        btnvecuoi.setMaximumSize(new java.awt.Dimension(50, 20));
        btnvecuoi.setMinimumSize(new java.awt.Dimension(50, 20));
        btnvecuoi.setPreferredSize(new java.awt.Dimension(50, 20));
        btnvecuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvecuoiActionPerformed(evt);
            }
        });
        add(btnvecuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 870, 130, 40));

        btntien.setBackground(new java.awt.Color(173, 139, 115));
        btntien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btntien.setForeground(new java.awt.Color(255, 255, 255));
        btntien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon tiến.png"))); // NOI18N
        btntien.setText("Tiến");
        btntien.setMaximumSize(new java.awt.Dimension(50, 20));
        btntien.setMinimumSize(new java.awt.Dimension(50, 20));
        btntien.setPreferredSize(new java.awt.Dimension(50, 20));
        btntien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntienActionPerformed(evt);
            }
        });
        add(btntien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 870, 130, 40));

        btntruoc.setBackground(new java.awt.Color(173, 139, 115));
        btntruoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btntruoc.setForeground(new java.awt.Color(255, 255, 255));
        btntruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon trước.png"))); // NOI18N
        btntruoc.setText("Trước");
        btntruoc.setMaximumSize(new java.awt.Dimension(50, 20));
        btntruoc.setMinimumSize(new java.awt.Dimension(50, 20));
        btntruoc.setPreferredSize(new java.awt.Dimension(50, 20));
        btntruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruocActionPerformed(evt);
            }
        });
        add(btntruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 870, 120, 40));

        btnvedau.setBackground(new java.awt.Color(173, 139, 115));
        btnvedau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvedau.setForeground(new java.awt.Color(255, 255, 255));
        btnvedau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon về đầu.png"))); // NOI18N
        btnvedau.setText("Về đầu");
        btnvedau.setMaximumSize(new java.awt.Dimension(50, 20));
        btnvedau.setMinimumSize(new java.awt.Dimension(50, 20));
        btnvedau.setPreferredSize(new java.awt.Dimension(50, 20));
        btnvedau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvedauActionPerformed(evt);
            }
        });
        add(btnvedau, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 870, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void tblhoadonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblhoadonAncestorAdded
        // TODO add your handling code here:
        fillToTable();
    }//GEN-LAST:event_tblhoadonAncestorAdded

    private void tblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonMouseClicked
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_tblhoadonMouseClicked

    private void cboHTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHTTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHTTTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTiemkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiemkiemActionPerformed
        // TODO add your handling code here:
        fillToTableTheoDieuKien();
    }//GEN-LAST:event_btnTiemkiemActionPerformed

    private void btnvecuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvecuoiActionPerformed
        // TODO add your handling code here:
        moveLast();
    }//GEN-LAST:event_btnvecuoiActionPerformed

    private void btntienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntienActionPerformed
        // TODO add your handling code here:
        moveNext();
    }//GEN-LAST:event_btntienActionPerformed

    private void btntruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruocActionPerformed
        // TODO add your handling code here:
        movePrevious();
    }//GEN-LAST:event_btntruocActionPerformed

    private void btnvedauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvedauActionPerformed
        // TODO add your handling code here:
        moveFirst();
    }//GEN-LAST:event_btnvedauActionPerformed
    
    public void fillToTableTheoDieuKien() {
       
    try {
         HoaDonImpl dao = new HoaDonImpl(); 
        String keyword = txtFind.getText().trim();
        List<HoaDon> list = dao.findByKeyword(keyword);

        DefaultTableModel model = (DefaultTableModel) tblhoadon.getModel();
        model.setRowCount(0);

        if (list.isEmpty()) {
            UDialog.alert("Không tìm thấy .");
            return;
        }

        for (HoaDon hd : list) {
            Object[] row = {
              hd.getMaHD(),
                hd.getMaBan(),
                hd.getMaNV(),
                hd.getNgayLap(),
                hd.getTongTien(),
                hd.getHinhThucTT(),
                hd.getTenKH()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        UDialog.alert("Lỗi khi tìm!");
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTiemkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btntien;
    private javax.swing.JButton btntruoc;
    private javax.swing.JButton btnvecuoi;
    private javax.swing.JButton btnvedau;
    private javax.swing.JComboBox<String> cboHTTT;
    private com.toedter.calendar.JDateChooser dcNgayLap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtmaban;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(Model.HoaDon entity) {
         txtmahoadon.setText(entity.getMaHD());
         txtTenKhach.setText(entity.getTenKH());
    txtmanv.setText(UAuth.user.getMaNV());
    txtmaban.setText(entity.getMaBan());
    txttongtien.setText(String.valueOf(entity.getTongTien()));
    dcNgayLap.setDate(entity.getNgayLap());
    String httt = entity.getHinhThucTT();
    if ("Tiền mặt".equals(httt)) {
        cboHTTT.setSelectedItem("Tiền mặt");
    } else {
        cboHTTT.setSelectedItem("Chuyển khoản");
    }

    }

    @Override
    public Model.HoaDon getForm() {
             HoaDon hd = new HoaDon();
    HoaDonImpl vtDao = new HoaDonImpl();
    hd.setTenKH(txtTenKhach.getText().trim());
    hd.setMaHD(txtmahoadon.getText().trim());
    hd.setMaNV(txtmanv.getText().trim());
    hd.setMaBan(txtmaban.getText().trim());
    hd.setTongTien(Double.parseDouble(txttongtien.getText().trim()));
    hd.setNgayLap(dcNgayLap.getDate());
    String httt = cboHTTT.getSelectedItem().toString();
    hd.setHinhThucTT(httt);
    return hd;
    }

    @Override
    public void fillToTable() {
         DefaultTableModel model = (DefaultTableModel) tblhoadon.getModel();
        model.setRowCount(0);
        items = dao.findAll();
        items.forEach(item -> {
            Object[] rowData = {
                item.getMaHD(),
                item.getMaBan(),
                item.getMaNV(),
                item.getNgayLap(),
                item.getTongTien(),
                item.getHinhThucTT(),
                item.getTenKH()
            };
            model.addRow(rowData);
        });
    }

    @Override
    public void edit() {
        HoaDon entity = items.get(tblhoadon.getSelectedRow());
        this.setForm(entity);
    }

    @Override
    public void create() {
        if (!Checkall()) return; 

        if (UDialog.confirm("Bạn thực sự muốn thêm?")) {
            HoaDon entity = this.getForm();
            dao.create(entity);
            this.fillToTable();
            this.clear();
            UDialog.alert("Đã thêm thành công");
        }
    }

    @Override
    public void update() {
        if (UDialog.confirm("Bạn thực sự muốn cập nhật thông tin này?")) {
            HoaDon hd = this.getForm();
            dao.update(hd);
            this.fillToTable();
            this.clear();
            UDialog.alert("Cập nhật thành công!");
        }
    }

    @Override
    public void delete() {
        int row = tblhoadon.getSelectedRow();
    if (row == -1) {
        UDialog.alert("Vui lòng chọn hóa đơn cần xóa!");
        return;
    }

    String maNV = tblhoadon.getValueAt(row, 0).toString();
    if (UDialog.confirm("Bạn chắc chắn muốn xóa hóa đơn này?")) {
        dao.deleteById(maNV);
        this.fillToTable();
        this.clear();
        UDialog.alert("Xóa thành công!");
    }
    }

    @Override
    public void clear() {
        this.setForm(new HoaDon());
    }

    @Override
    public void moveFirst() {
        int currentIndex = tblhoadon.getSelectedRow();
        if (currentIndex == 0) {
            UDialog.alert( "Đã ở vị trí đầu tiên rồi!");
        } else {
            this.moveTo(0);
        }
    }

    @Override
    public void movePrevious() {
        this.moveTo(tblhoadon.getSelectedRow() - 1);
    }

    @Override
    public void moveNext() {
        this.moveTo(tblhoadon.getSelectedRow() + 1);
    }

    @Override
    public void moveLast() {
        this.moveTo(tblhoadon.getRowCount() - 1);
    }

    @Override
    public void moveTo(int rowIndex) {
        if (rowIndex < 0) {
        this.moveLast();
    } else if (rowIndex >= tblhoadon.getRowCount()) {
        this.moveFirst();
    } else {
        tblhoadon.clearSelection();
        tblhoadon.setRowSelectionInterval(rowIndex, rowIndex);
        this.edit();
    }
    }


    @Override
    public boolean Checkall() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
