/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ModelController.MonAnController;
import DAO.ModelDAO.MonAnDAO;
import DAO.impl.MonAnImpl;
import Model.MonAn;
import static Util.UAuth.clear;
import Util.UDialog;
import Util.UQuery;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ExpertBook
 */
public class QLMA extends javax.swing.JPanel implements MonAnController{
    MonAnDAO dao = new MonAnImpl();
    List<MonAn> items = new ArrayList<>();
    private String tenAnh;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLMA.class.getName());
    /**
     * Creates new form QLMA
     */
    public QLMA(boolean visible) {
        initComponents();
    setButtonVisible(visible);
    }
    public void setButtonVisible(boolean visible) {
    jButton1.setVisible(visible);
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTien = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();
        btnDau = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();
        lblAnh = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtDonGia = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        txtMaLoai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnTiemkiem = new javax.swing.JButton();
        btnvecuoi = new javax.swing.JButton();
        btntien = new javax.swing.JButton();
        btntruoc = new javax.swing.JButton();
        btnvedau = new javax.swing.JButton();

        btnTien.setBackground(new java.awt.Color(173, 139, 115));
        btnTien.setText("Tiến");
        btnTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienActionPerformed(evt);
            }
        });

        btnTruoc.setBackground(new java.awt.Color(173, 139, 115));
        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnDau.setBackground(new java.awt.Color(173, 139, 115));
        btnDau.setText("Về đầu");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1830, 1070));

        jPanel4.setBackground(new java.awt.Color(173, 139, 115));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản Lý Món Ăn");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1802, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Đơn giá", "Mô tả", "Hình ảnh", "Mã loại"
            }
        ));
        tblMonAn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblMonAnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonAnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMonAn);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1920, 360));

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, 200, 174));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon thêm ảnh.png"))); // NOI18N
        jButton2.setText("Chọn ảnh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 370, -1, -1));

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 290, -1));

        txtMoTa.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        add(txtMoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 290, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Đơn giá:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Mô tả:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mã món:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tên món:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Mã loại:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, -1));

        txtMaMon.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtMaMon.setEnabled(false);
        add(txtMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 290, -1));

        txtTenMon.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        add(txtTenMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 290, -1));

        txtMaLoai.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        add(txtMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 290, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon thêm.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 120, 110, 40));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon xóa.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 120, 110, 40));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon sửa.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 120, 110, 40));

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon làm mới.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 120, 130, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel14.setText("Tìm kiếm:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 280, 40));

        btnTiemkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnTiemkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiemkiemActionPerformed(evt);
            }
        });
        add(btnTiemkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        btnvecuoi.setBackground(new java.awt.Color(173, 139, 115));
        btnvecuoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvecuoi.setForeground(new java.awt.Color(255, 255, 255));
        btnvecuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon về cuối.png"))); // NOI18N
        btnvecuoi.setText("Về cuối");
        btnvecuoi.setMaximumSize(new java.awt.Dimension(50, 20));
        btnvecuoi.setMinimumSize(new java.awt.Dimension(50, 20));
        btnvecuoi.setPreferredSize(new java.awt.Dimension(50, 20));
        btnvecuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvecuoiActionPerformed(evt);
            }
        });
        add(btnvecuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 840, 130, 40));

        btntien.setBackground(new java.awt.Color(173, 139, 115));
        btntien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btntien.setForeground(new java.awt.Color(255, 255, 255));
        btntien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon tiến.png"))); // NOI18N
        btntien.setText("Tiến");
        btntien.setMaximumSize(new java.awt.Dimension(50, 20));
        btntien.setMinimumSize(new java.awt.Dimension(50, 20));
        btntien.setPreferredSize(new java.awt.Dimension(50, 20));
        btntien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntienActionPerformed(evt);
            }
        });
        add(btntien, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 840, 130, 40));

        btntruoc.setBackground(new java.awt.Color(173, 139, 115));
        btntruoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btntruoc.setForeground(new java.awt.Color(255, 255, 255));
        btntruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon trước.png"))); // NOI18N
        btntruoc.setText("Trước");
        btntruoc.setMaximumSize(new java.awt.Dimension(50, 20));
        btntruoc.setMinimumSize(new java.awt.Dimension(50, 20));
        btntruoc.setPreferredSize(new java.awt.Dimension(50, 20));
        btntruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruocActionPerformed(evt);
            }
        });
        add(btntruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 840, 120, 40));

        btnvedau.setBackground(new java.awt.Color(173, 139, 115));
        btnvedau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvedau.setForeground(new java.awt.Color(255, 255, 255));
        btnvedau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon về đầu.png"))); // NOI18N
        btnvedau.setText("Về đầu");
        btnvedau.setMaximumSize(new java.awt.Dimension(50, 20));
        btnvedau.setMinimumSize(new java.awt.Dimension(50, 20));
        btnvedau.setPreferredSize(new java.awt.Dimension(50, 20));
        btnvedau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvedauActionPerformed(evt);
            }
        });
        add(btnvedau, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 840, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTienActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDauActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn ảnh từ máy");
        chooser.setFileFilter(new FileNameExtensionFilter("Hình ảnh", "jpg", "png", "jpeg", "gif"));

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fileChon = chooser.getSelectedFile();
            String tenFile = fileChon.getName();

            File thuMucLuu = new File("src/img");
            if (!thuMucLuu.exists()) {
                thuMucLuu.mkdirs();
            }

            File fileDich = new File(thuMucLuu, tenFile);
            try {
                // Copy ảnh vào thư mục dự án
                Files.copy(fileChon.toPath(), fileDich.toPath(), StandardCopyOption.REPLACE_EXISTING);
                tenAnh = tenFile;

                // Hiển thị ảnh với kích thước 150x150
                ImageIcon icon = new ImageIcon("src/img/" + tenFile);
                Image img = icon.getImage().getScaledInstance(200, 174, Image.SCALE_SMOOTH);
                lblAnh.setIcon(new ImageIcon(img));
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi sao chép ảnh!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblMonAnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblMonAnAncestorAdded
        // TODO add your handling code here:
         DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Mã món", "Tên món", "Đơn giá","Mô tả","Hình ảnh", "Mã loại"},
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa bất kỳ ô nào
            }
        };
        tblMonAn.setModel(model);

        fillToTable();
    }//GEN-LAST:event_tblMonAnAncestorAdded

    private void tblMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonAnMouseClicked
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_tblMonAnMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        create();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTiemkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiemkiemActionPerformed
        // TODO add your handling code here:
        fillToTableTheoDieuKien();
    }//GEN-LAST:event_btnTiemkiemActionPerformed

    private void btnvecuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvecuoiActionPerformed
        // TODO add your handling code here:
        moveLast();
    }//GEN-LAST:event_btnvecuoiActionPerformed

    private void btntienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntienActionPerformed
        // TODO add your handling code here:
        moveNext();
    }//GEN-LAST:event_btntienActionPerformed

    private void btntruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruocActionPerformed
        // TODO add your handling code here:
        movePrevious();
    }//GEN-LAST:event_btntruocActionPerformed

    private void btnvedauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvedauActionPerformed
        // TODO add your handling code here:
        moveFirst();
    }//GEN-LAST:event_btnvedauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTiemkiem;
    private javax.swing.JButton btnTien;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btntien;
    private javax.swing.JButton btntruoc;
    private javax.swing.JButton btnvecuoi;
    private javax.swing.JButton btnvedau;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
private void hienThiAnh(String duongDan) {
    ImageIcon icon = new ImageIcon(duongDan);
    Image img = icon.getImage().getScaledInstance(200, 174, Image.SCALE_SMOOTH);
    lblAnh.setIcon(new ImageIcon(img));
    }
    @Override
public void setForm(MonAn entity) {
    txtMaMon.setText(entity.getMaMon());
    txtTenMon.setText(entity.getTenMon());
    txtDonGia.setText(String.valueOf(entity.getDonGia()));
    txtMoTa.setText(entity.getMoTa());
    txtMaLoai.setText(String.valueOf(entity.l.getMaLoai()));
    String tenAnh = entity.getHinhAnh(); // chỉ là tên file, ví dụ: nv01.jpg

    if (tenAnh != null && !tenAnh.isEmpty()) {
        String fullPath = "src/img/" + tenAnh; // Đường dẫn mới
        File file = new File(fullPath);

        if (file.exists()) {
            ImageIcon icon = new ImageIcon(fullPath);
            Image img = icon.getImage().getScaledInstance(206, 176, Image.SCALE_SMOOTH);
            lblAnh.setIcon(new ImageIcon(img));
        } else {
            lblAnh.setIcon(null);
            System.out.println("Không tìm thấy ảnh: " + fullPath);
        }
    } else {
        lblAnh.setIcon(null);
    }

    }


@Override
public MonAn getForm() {
    MonAn m = new MonAn();
    m.setMaMon(txtMaMon.getText().trim());
    m.setTenMon(txtTenMon.getText().trim());
    try {
        m.setDonGia(Double.parseDouble(txtDonGia.getText().trim()));
    } catch (NumberFormatException e) {
        m.setDonGia(0);
    }
    m.setMoTa(txtMoTa.getText().trim());
    m.setHinhAnh(tenAnh); 
    m.l.setMaLoai(Integer.parseInt(txtMaLoai.getText().trim()));
    return m;
}

@Override
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblMonAn.getModel();
    model.setRowCount(0);
    items = dao.findAll();

   items.forEach(mon -> {
        Object[] row = {
                mon.getMaMon(),
                mon.getTenMon(),
                mon.getDonGia(),
                mon.getMoTa(),
                mon.getHinhAnh(),
                mon.l.getMaLoai(),
        };
        model.addRow(row);
    });
}

@Override
public void create() {
    if (!Checkall()) return;
    if (UDialog.confirm("Bạn chắc chắn muốn thêm món ăn này?")) {
        MonAn m = getForm();
        dao.create(m);
        fillToTable();
        clear();
        UDialog.alert("Thêm thành công");
    }
}

@Override
public void update() {
    if (!Checkall()) return;
    if (UDialog.confirm("Bạn chắc chắn muốn cập nhật món ăn này?")) {
        MonAn m = getForm();
        dao.update(m);
        fillToTable();
        clear();
        UDialog.alert("Cập nhật thành công");
    }
}

@Override
public void delete() {
    int row = tblMonAn.getSelectedRow();
    if (row == -1) {
        UDialog.alert("Vui lòng chọn dòng cần xóa!");
        return;
    }
    String ma = tblMonAn.getValueAt(row, 0).toString();
    if (UDialog.confirm("Bạn chắc chắn muốn xóa món ăn này?")) {
        dao.deleteById(ma);
        fillToTable();
        clear();
        UDialog.alert("Xóa thành công");
    }
}
@Override
public void moveFirst() {
    int currentIndex = tblMonAn.getSelectedRow();
    if (currentIndex == 0) {
        UDialog.alert("Đã ở vị trí đầu tiên rồi!");
    } else {
        this.moveTo(0);
    }
}

@Override
public void movePrevious() {
    this.moveTo(tblMonAn.getSelectedRow() - 1);
}

@Override
public void moveNext() {
    this.moveTo(tblMonAn.getSelectedRow() + 1);
}

@Override
public void moveLast() {
    this.moveTo(tblMonAn.getRowCount() - 1);
}

@Override
public void moveTo(int rowIndex) {
    if (rowIndex < 0) {
        this.moveLast();
    } else if (rowIndex >= tblMonAn.getRowCount()) {
        this.moveFirst();
    } else {
        tblMonAn.clearSelection();
        tblMonAn.setRowSelectionInterval(rowIndex, rowIndex);
        this.edit();
    }
}

@Override
public boolean Checkall() {
    if (txtTenMon.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập tên món!");
        txtTenMon.requestFocus();
        return false;
    }

    if (txtDonGia.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập đơn giá!");
        txtDonGia.requestFocus();
        return false;
    }

    try {
        Double.parseDouble(txtDonGia.getText().trim());
    } catch (NumberFormatException e) {
        UDialog.alert("Đơn giá phải là số!");
        txtDonGia.requestFocus();
        return false;
    }

    if (txtMoTa.getText().trim().isEmpty()) {
        UDialog.alert("Vui lòng nhập mô tả món!");
        txtMoTa.requestFocus();
        return false;
    }
    return true;
}

public void fillToTableTheoDieuKien(){
    try {
        MonAnImpl dao = new MonAnImpl(); 
        String keyword = txtFind.getText().trim();
        List<MonAn> list = dao.findByKeyword(keyword);

        DefaultTableModel model = (DefaultTableModel) tblMonAn.getModel();
        model.setRowCount(0);

        if (list.isEmpty()) {
            UDialog.alert("Không tìm thấy món ăn nào.");
            return;
        }

        for (MonAn mon : list) {
            Object[] row = {
                mon.getMaMon(),
                mon.getTenMon(),
                mon.getDonGia(),
                mon.getMoTa(),
                mon.getHinhAnh(),
                mon.l.getMaLoai(),

                
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        UDialog.alert("Lỗi khi tìm món ăn!");
    }
}
@Override
public void edit() {
    MonAn entity = items.get(tblMonAn.getSelectedRow());
    this.setForm(entity);
}

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        this.setForm(new MonAn());
    }
}
