/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.impl.VoucherImpl;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class voucher extends javax.swing.JPanel {

    /**
     * Creates new form voucher
     */
    private String maKH;
    private VoucherImpl voucherDAO = new VoucherImpl();
    
    public voucher(String maKH) {
        this.maKH = maKH;
        initComponents();
        capNhatTichDiem();
    }
    private void capNhatTichDiem() {
        double tong = voucherDAO.layTongChiTieu(maKH);
        int diem = (int) (tong / 1_000_000);   
        txtatichdiem.setText("Tổng chi tiêu: " + tong + " VNĐ\n"+"Bạn đã tích được " + diem + "điểm.\n(Mỗi điểm = 1.000.000 VNĐ chi tiêu)");
    }
    public void refresh() {
    capNhatTichDiem();
}
     public static void run(String maKH) {
    javax.swing.SwingUtilities.invokeLater(() -> {
        javax.swing.JFrame frame = new javax.swing.JFrame("Voucher Khách Hàng");
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.setSize(1320, 630);
        frame.setLocationRelativeTo(null);
        frame.setContentPane(new voucher(maKH)); // Gắn JPanel vào JFrame
        frame.setVisible(true);
    });
}
     public static void main(String[] args) {
    run("KH001"); // Thay "KH001" bằng mã khách hàng có trong DB
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtatichdiem = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 251, 233));
        setMinimumSize(new java.awt.Dimension(1320, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(173, 139, 115));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KHUYẾN MÃI GIẢM GIÁ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addComponent(jLabel1)
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TÍCH ĐIỂM ĐỔI QUÀ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 240, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Mỗi lần ghé là một lần tích điểm – Đổi 5 điểm, nhận ngay món ăn miễn phí!");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 20));

        txtatichdiem.setBackground(new java.awt.Color(255, 251, 233));
        txtatichdiem.setColumns(20);
        txtatichdiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtatichdiem.setRows(5);
        jScrollPane1.setViewportView(txtatichdiem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 660, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/qruci.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtatichdiem;
    // End of variables declaration//GEN-END:variables
}
