/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.ViewDatBan;

import DAO.ModelDAO.DatBanDAO;
import DAO.impl.DatBanimpl;
import Model.DatBan;
import Model.DatBanINFOR;
import Util.UDialog;
import Util.UJdbc;
import View.IN4;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.time.LocalTime;
import java.util.Date;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author baoha
 */
public class ConfirmDatBan extends javax.swing.JDialog {
private final Animator animator;
private boolean show = true;
private Frame frame;
private DatBanimpl service;

public ConfirmDatBan(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    
    setUndecorated(true);        // THÊM DÒNG NÀY TRƯỚC setOpacity()
    setOpacity(0f);              // Đặt độ mờ ban đầu
    initComponents();            // Khởi tạo giao diện

    service = new DatBanimpl();
    this.frame = parent;
    getContentPane().setBackground(Color.WHITE);
    
    TimingTarget target = new TimingTargetAdapter() {
        @Override
        public void timingEvent(float fraction) {
            if (show) {
                setOpacity(fraction);
            } else {
                setOpacity(1f - fraction);
            }
        }

        @Override
        public void end() {
            if (!show) {
                setVisible(false);
            }
        }
    };

    animator = new Animator(200, target);
    animator.setResolution(0);
    animator.setAcceleration(0.5f);
}
public void showConfirmDatBan(List<DatBanINFOR> list) {
    setLocationRelativeTo(frame);

    if (list.isEmpty()) return;
    DatBanINFOR first = list.get(0);

    lbMessage.setText("Bạn có chắc chắn đặt bàn số " + first.getMaBan()+ " cho " + first.getSoNguoi() + " người vào lúc " + first.getGioDat() + " không?");
    lbTotal.setText("Ngày đặt: " + first.getNgayDat().toString());

    // Xóa các listener cũ tránh add nhiều lần
    for (ActionListener al : btnXacNhan.getActionListeners()) {
        btnXacNhan.removeActionListener(al);
    }

    btnXacNhan.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            for (DatBanINFOR info : list) {
                try {
                    service.executeProcedureDatBan(
                        info.getTenKH(),
                        info.getMaBan(),
                        new java.sql.Date(info.getNgayDat().getTime()),
                        java.sql.Time.valueOf(info.getGioDat()),
                        info.getSoNguoi(),
                        info.getMaNV(),
                        info.getHTTT(),
                        info.getMaMon(),
                        info.getSoLuong(),
                        info.getGhiChu()
                    );
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(null, "✅ Đặt bàn và món thành công!");
            setVisible(false); // Ẩn dialog sau khi xác nhận
        }
    });

    animator.start();
    setVisible(true);
}





private void closeMenu() {
        if (animator.isRunning()) {
            animator.stop();
        }
        show = false;
        animator.start();
    }
    
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gp = new GradientPaint(0, 0, Color.decode("#516395"), 0, getHeight(), Color.decode("#614385"));
        g2.setPaint(gp);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponents(g);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbMessage = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnXacNhan = new View.themvagiam();
        btnHuy = new View.themvagiam();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(173, 139, 115))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(173, 139, 115));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 139, 115));
        jLabel2.setText("XÁC NHẬN ĐẶT BÀN?");

        lbMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMessage.setForeground(new java.awt.Color(173, 139, 115));
        lbMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage.setText("Message");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(173, 139, 115));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("TOTAL");

        btnXacNhan.setBackground(new java.awt.Color(173, 139, 115));
        btnXacNhan.setForeground(new java.awt.Color(0, 255, 0));
        btnXacNhan.setText("Xác nhận");

        btnHuy.setBackground(new java.awt.Color(173, 139, 115));
        btnHuy.setForeground(new java.awt.Color(255, 0, 0));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ask.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel3)
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(lbMessage)
                    .addGap(18, 18, 18)
                    .addComponent(lbTotal)
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 70, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        closeMenu();
    }//GEN-LAST:event_btnHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.themvagiam btnHuy;
    private View.themvagiam btnXacNhan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbTotal;
    // End of variables declaration//GEN-END:variables
}
